<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Desktop-22" failures="0" tests="2" name="Dashboard.Login_Logout_Test_Cases.TC_01_TC_18_Verify_existing_user_can_authenticate_with_correct_credentials" time="6.629" errors="0" timestamp="2025-06-04T12:41:03 IST" skipped="0">
  <testcase classname="Dashboard.Login_Logout_Test_Cases.TC_01_TC_18_Verify_existing_user_can_authenticate_with_correct_credentials" name="Verify_logout_functionality" time="1.788"/>
  <system-out/>
  <testcase classname="Dashboard.Login_Logout_Test_Cases.TC_01_TC_18_Verify_existing_user_can_authenticate_with_correct_credentials" name="Verify_existing_user_can_authenticate_with_correct_credentials_SOFT_682_F2" time="4.841"/>
  <system-out/>
</testsuite> <!-- Dashboard.Login_Logout_Test_Cases.TC_01_TC_18_Verify_existing_user_can_authenticate_with_correct_credentials -->
